# -*- coding: utf-8 -*-
"""hw3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RUITz9oN7zWMGiTRiViXJJkox_aQOu22
"""

!pip3 install ColabTurtle
from ColabTurtle.Turtle import *
initializeTurtle()

for i in range(8):
  forward(50)
  right(45)

!pip3 install ColabTurtle
from ColabTurtle.Turtle import *
initializeTurtle()

color('red')
for i in range(5):
    forward(100)
    right(144)

penup()
goto(150, 150)
pendown()

color('blue')
for i in range(5):
    forward(100)
    right(144)

!pip3 install ColabTurtle
from ColabTurtle.Turtle import *
initializeTurtle()


speed(5)
bgcolor("lightblue")

penup()
goto(150, 150)
pendown()
color("yellow")
for _ in range(36):
    forward(10)
    right(10)